import os
import random


PATH_EXCAVADORES = os.path.join('archivos', 'excavadores.csv')
PATH_TESOROS = os.path.join('archivos', 'tesoros.csv')
PATH_CONSUMIBLE = os.path.join('archivos', 'consumibles.csv')
PATH_ARENAS = os.path.join('archivos', 'arenas.csv')
DIAS_TOTALES_TORNEO = 0
ARENA_INICIAL = random.choice(['normal', 'mojada', 'rocosa', 'magnetica'])
CANTIDAD_EXCAVADORES_INICIALES = 0
METROS_META = 0
DIAS_TOTALES_TORNEO = 0
PROB_ENCONTRAR_ITEM = 0.3
PROB_ENCONTRAR_TESORO = 0.3
PROB_ENCONTRAR_CONSUMIBLE = 0.7
PROB_INICIAR_EVENTO = 0
PROB_LLUVIA = 0
PROB_TERREMOTO = 0
PROB_DERRUMBE = 0
METROS_PERDIDOS_DERRUMBE = 0
FELICIDAD_PERDIDA = 0
POND_ARENA_NORMAL = random.uniform(0.1, 1)
FELICIDAD_ADICIONAL_DOCENCIO = 0
FUERZA_ADICIONAL_DOCENCIO = 0
ENERGIA_PERDIDA_DOCENCIO = 0
ENERGIA_ADICIONAL_TAREO = 0
SUERTE_ADICIONAL_TAREO = 0
EDAD_ADICIONAL_TAREO = 0
FELICIDAD_PERDIDA_TAREO = 0

